[package]
org = "com_comparision"
name = "social_media"
version = "0.0.1"
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true

[persist.social_media.storage.mysql]
host = "localhost"
port = 3306
user = "social_media_user"
password = "dummypassword"
database = "social_media_database"

