moderate = true

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
samplerParam=1.0

[social_media]
host = "localhost"
port = 3306
user = "social_media_user"
password = "dummypassword"
database = "social_media_database"
